export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS";
export const GET_TODOS_FAILED = "GET_TODOS_FAILED";

export const GET_TODOS_REQUESTED = "GET_TODOS_REQUESTED";
export const GET_TODO_REQUESTED = "GET_TODO_REQUESTED";
export const ADD_TODO_REQUESTED = "ADD_TODO_REQUESTED";
export const REMOVE_TODO_REQUESTED = "REMOVE_TODO_REQUESTED";
export const UPDATE_TODO_REQUESTED = "UPDATE_TODO_REQUESTED";
